version: "3"

services:
    app:
        image: foodapp_converter
        build: 
            context: .
            dockerfile: ./docker/Dockerfile
        restart: "always"
        stdin_open: true
        volumes:
           - type: bind
             source: .
             target: /usr/src/app
#           - /usr/src/app/node_modules
        environment:
            NODE_ENV: development
        ports:
            - 3000:3000
            # - 9229:9229
        # depends_on:
        #     - db
        #     - api
        # command: bash -c 'while !</dev/tcp/api/3000; do sleep 1; done; npm run start'
        command: npm run dev
